account-lifetime = 86400000 # 1 day.
depth = 3600000 # 1 hour.
debug = true
host = "0.0.0.0:16736"

[[chain]]
name = "rococo"
endpoints = [
    "wss://node-polkadot.zymologia.fi",
]

[chain.native]
name = "DOTL"
decimals = 10

[[chain]]
name = "statemint"
endpoints = [
    "wss://node-polkadot-ah.zymologia.fi"
]

[[chain.asset]]
name = "USDC"
id = 1337

[[chain.asset]]
name = "USDt"
id = 1984
